


version: "3.9"
services:
  bank-browser:
    container_name: bank-browser
    build:
      context: ./client/browser
      dockerfile: Dockerfile
    ports:
      - target: 5173
        published: 5173
        host_ip: 127.0.0.1 # ensures that port isn't exposed from host machine as well
        protocol: tcp
    volumes:
      - type: bind
        source: ${CLIENT_BROWSER_PATH}/src
        target: /app/src
      - type: bind
        source: ${CLIENT_BROWSER_PATH}/public
        target: /app/public
      - type: bind
        source: ${CLIENT_BROWSER_PATH}/tsconfig.json
        target: /app/tsconfig.json
      - type: bind
        source: ${CLIENT_BROWSER_PATH}/tsconfig.node.json
        target: /app/tsconfig.node.json
      - type: bind
        source: ${CLIENT_BROWSER_PATH}/vite.config.ts
        target: /app/vite.config.ts
      - type: volume
        target: /app/node_modules # avoid bringing in node_modules
      - type: volume
        target: /app/.yarn # avoid bringing in .yarn
  db:
    container_name: bank-db
    image: postgres:16.2-alpine3.19
    ports:
      - target: 5432
        published: 5434
        host_ip: 127.0.0.1
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "bank"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
