version: "3.9"
services:
  bank-browser:
    container_name: bank-browser
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 5173
        published: 5173
        host_ip: 127.0.0.1 # ensures that port isn't exposed from host machine as well
        protocol: tcp
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./public
        target: /app/public
      - type: bind
        source: ./tsconfig.json
        target: /app/tsconfig.json
      - type: bind
        source: ./tsconfig.node.json
        target: /app/tsconfig.node.json
      - type: bind
        source: ./vite.config.ts
        target: /app/vite.config.ts
      - type: volume
        target: /app/node_modules # avoid bringing in node_modules
      - type: volume
        target: /app/.yarn # avoid bringing in .yarn

