ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.sigurof.bankybank.ApplicationKt.module
db:
  jdbc:
    user: postgres
    port: 5432
    database: postgres
    url: "jdbc:postgresql://bank-app-db"
    password: bank


